scripttable.EndTerminalA=endterminal5a

scripttable.EndTerminalB=endterminal5b

scripttable.NextLevelTrigger=nextlevel5a

scripttable.NextLevelTrigger2=nextlevel5b

scripttable.OpenEndDoor1=opendoors5_1

scripttable.OpenEndDoor2=opendoors5_2

scripttable.LevelStart=start5

scripttable.TeleporterDoorTrigger=teledoor5

scripttable.BossTrigger=boss5